version: "3.7"

networks:
  corp:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      args:
        NODE_ENV: "production"
        BUILD_FLAG: "--prod"
    image: api
    ports:
      - "3333:3333"
    restart: on-failure
    environment:
      NODE_ENV: "production"
      PORT: 3333

  admin-panel:
    container_name: admin-panel
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/admin-panel/Dockerfile
      args:
        NODE_ENV: "production"
        BUILD_FLAG: "--prod"
    image: webmob:nx-dev
    ports:
      - "3334:80"
    environment:
      NODE_ENV: "production"
      PORT: 8095
    networks:
      - corp
    restart: on-failure

